name: trees
channels:
  - conda-forge
dependencies:
  - cartopy
  - colorcet
  - geopandas
  - intake
  - intake-xarray
  - numpy
  - pandas
  - rasterio
  - tqdm
  - xarray
  - bokeh/label/dev::bokeh
  - pyviz/label/dev::geoviews
  - pyviz/label/dev::holoviews
  - pyviz/label/dev::hvplot
  - pyviz/label/dev::datashader
  - pyviz/label/dev::panel
  - pip:
    - rio-toa
